name: Publish new release

on:
  push:
    branches: 
      - main

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: zip -r compris.zip compris -x "*.DS_Store"
      - name: Upload style to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_RELEASE_TOKEN }}
          file: compris.zip
